# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: slackbot.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'slackbot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eslackbot.proto\x12\x08slackbot\"\\\n\x0eMessageRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\x12\n\n\x02ts\x18\x03 \x01(\t\x12\x11\n\tthread_ts\x18\x04 \x01(\t\x12\x0c\n\x04user\x18\x05 \x01(\t\";\n\x0fMessageResponse\x12\x12\n\nreply_text\x18\x01 \x01(\t\x12\x14\n\x0cshould_reply\x18\x02 \x01(\x08\x32P\n\x08SlackBot\x12\x44\n\rHandleMessage\x12\x18.slackbot.MessageRequest\x1a\x19.slackbot.MessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'slackbot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST']._serialized_start=28
  _globals['_MESSAGEREQUEST']._serialized_end=120
  _globals['_MESSAGERESPONSE']._serialized_start=122
  _globals['_MESSAGERESPONSE']._serialized_end=181
  _globals['_SLACKBOT']._serialized_start=183
  _globals['_SLACKBOT']._serialized_end=263
# @@protoc_insertion_point(module_scope)
